# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
[┌─](bold #89b4fa)$directory$git_branch$git_status$nodejs$rust$golang$python
[└─>](bold #89b4fa) """

# Character
[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

# Directory
[directory]
style = "bold #89b4fa"
truncation_length = 3
truncation_symbol = "…/"
read_only = " 󰌾"

# Git branch
[git_branch]
symbol = " "
style = "bold #cba6f7"
format = "[$symbol$branch]($style) "

# Git status
[git_status]
style = "bold #f38ba8"
format = "([\\[$all_status$ahead_behind\\]]($style) )"

# Languages
[nodejs]
symbol = " "
style = "bold #a6e3a1"
format = "[$symbol($version )]($style)"

[rust]
symbol = " "
style = "bold #fab387"
format = "[$symbol($version )]($style)"

[golang]
symbol = " "
style = "bold #89dceb"
format = "[$symbol($version )]($style)"

[python]
symbol = " "
style = "bold #f9e2af"
format = "[$symbol($version )]($style)"

[cmd_duration]
min_time = 2_000
style = "bold #f9e2af"
format = "took [$duration]($style) "
